DROP DATABASE IF EXISTS TICKETING;
CREATE DATABASE TICKETING;
USE TICKETING;

-- create user 'dev@localhost' identified by '1234qwerty';
-- grant all privileges on *.* to 'dev@localhost';

CREATE TABLE TIPO_USUARIO(
ID_USUARIO INTEGER AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL
);

CREATE TABLE DISPOSITIVO(
ID_DISPOSITIVO INTEGER PRIMARY KEY AUTO_INCREMENT,
TIPO VARCHAR(30) NOT NULL
);

CREATE TABLE ESTADO(
ID_ESTADO INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE TIPO_INCIDENCIA(
ID_TIPOINCIDENCIA INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE PRIORIDAD(
ID_PRIORIDAD INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIO(
ID_USUARIO INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
NICKNAME VARCHAR(50) NOT NULL,
CONTRASENA VARCHAR(30) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
IS_ACTIVO BOOLEAN NOT NULL,
ID_TIPOUSUARIO INTEGER NOT NULL,
CONSTRAINT FK_TIPO_USUARIO FOREIGN KEY  (ID_TIPOUSUARIO) REFERENCES TIPO_USUARIO(ID_USUARIO)
);

CREATE TABLE INCIDENCIA(
ID_INICIDENCIA INTEGER PRIMARY KEY AUTO_INCREMENT,
FECHA_INICIO DATE NOT NULL,
FECHA_PUBLICACION DATE NOT NULL,
FECHA_FIN DATE,
ID_ESTADO INTEGER NOT NULL,
ID_USUARIO INTEGER NOT NULL,
ID_TIPOINCIDENCIA INTEGER NOT NULL,
ID_DISPOSITIVO INTEGER NOT NULL,
DESCRIPCION_INCIDENCIA VARCHAR(500),
DESCRIPCION_SOLUCION VARCHAR(500),
ID_PRIORIDAD INTEGER NOT NULL,
ID_USUARIO_TECNICO INTEGER,
CONSTRAINT FK_TECNICO FOREIGN KEY (ID_USUARIO_TECNICO) REFERENCES USUARIO (ID_USUARIO),
CONSTRAINT FK_DISPOSITIVO FOREIGN KEY (ID_DISPOSITIVO) REFERENCES DISPOSITIVO (ID_DISPOSITIVO),
CONSTRAINT FK_PRIORIDAD FOREIGN KEY (ID_PRIORIDAD) REFERENCES PRIORIDAD (ID_PRIORIDAD),
CONSTRAINT FK_TIPOINCIDENCIA FOREIGN KEY (ID_TIPOINCIDENCIA) REFERENCES TIPO_INCIDENCIA (ID_TIPOINCIDENCIA),
CONSTRAINT FK_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
CONSTRAINT FK_ID_USUARIO FOREIGN KEY  (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);



INSERT INTO TIPO_USUARIO VALUES (1 , 'ADMINISTRADOR');
INSERT INTO TIPO_USUARIO VALUES (2 , 'TECNICO');
INSERT INTO TIPO_USUARIO VALUES (3 , 'GESTOR');
INSERT INTO TIPO_USUARIO VALUES (9 , 'USUARIO');

INSERT INTO ESTADO VALUES (1,'ABIERTA');
INSERT INTO ESTADO VALUES (2,'EN TRAMITE');
INSERT INTO ESTADO VALUES (3,'CERRADA');
INSERT INTO ESTADO VALUES (4,'RESUELTA');

INSERT INTO PRIORIDAD VALUES (1,'ALTA');
INSERT INTO PRIORIDAD VALUES (2,'BAJA');
INSERT INTO PRIORIDAD VALUES (3,'MEDIA');

INSERT INTO TIPO_INCIDENCIA VALUES(1,'HARDWARE');
INSERT INTO TIPO_INCIDENCIA VALUES(2,'SOFTWARE');
INSERT INTO TIPO_INCIDENCIA VALUES(3,'RED');
INSERT INTO TIPO_INCIDENCIA VALUES(4,'PERIFERICOS');

INSERT INTO DISPOSITIVO VALUES(1,'ORDENADOR SOBREMESA');
INSERT INTO DISPOSITIVO VALUES(2,'ORDENADOR PORTÁTIL');
INSERT INTO DISPOSITIVO VALUES(3,'SMARTPHONE');
INSERT INTO DISPOSITIVO VALUES(4,'TECLADO');
INSERT INTO DISPOSITIVO VALUES(5,'RATÓN');

INSERT INTO USUARIO VALUES(1, 'José de Luis', 'López', 'JdLL', '1234qwerty', 'jdll@email.com',true,1);
INSERT INTO INCIDENCIA VALUES(1, NOW(), NOW(), NULL, 1, 1, 1, 1, 'Hola, soy Javier y tengo 4 años', null, 1,1);
INSERT INTO INCIDENCIA VALUES(2, NOW(), NOW(), NULL, 2, 1, 1, 1, 'Incidencia de nuevo', null, 1,1);



SELECT * FROM INCIDENCIA;