CREATE DATABASE TICKETING;

CREATE TABLE TIPO_USUARIO(
COD_USUARIO INTEGER AUTOINCREMENT PRIMARY KEY,
NOMBRE VARCHAR(30)
);
CREATE TABLE DISPOSITIVO(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
TIPO VARCHAR(15) NOT NULL,
MARCA VARCHAR(30) NOT NULL,
MODELO VARCHAR(30) NOT NULL,
DESCRIPCION VARCHAR(150)
);

CREATE TABLE ESTADO(
COD_ESTADO INTEGERPRIMARY KEY AUTOINCREMENT,
NOMBRE VARCHAR(50)NOT NULL
);

CREATE TABLE TIPO_INCIDENCIA(
COD_TIPOINCIDENCIA INTEGER PRIMARY KEY AUTOINCREMENT,
NOMBRE VARCHAR(50)NOT NULL
);

CREATE TABLE PRIORIDAD(
COD_PRIORIDAD INTEGER PRIMARY KEY AUTOINCREMENT,
NOMBRE VARCHAR(50)NOT NULL
);

CREATE TABLE INCIDENCIA(
ID_INICIDENCIA INTEGER PRIMARY KEY AUTOINCREMENT,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE,
ID_ESTADO INTEGER NOT NULL,
ID_TIPOINCIDENCIA INTEGER NOT NULL,
ID_DISPOSITIVO INTEGER NOT NULL,
DESCRIPCION_INCIDENCIA VARCAHR(500),
DESCRIPCION_SOLUCION VARCHAR(500),
ID_PRIORIDAD INTEGER NOT NULL,
ID_USUARIO INTEGER NOT NULL,
CONSTRAINT FK_DISPOSITIVO FOREIGN KEY (ID_DISPOSITIVO) REFERENCES DISPOSITIVO (ID),
CONSTRAINT FK_PRIORIDAD FOREIGN KEY (ID_PRIORIDAD) REFERENCES PRIORIDAD (COD_PRIORIDAD),
CONSTRAINT FK_TIPOINCIDENCIA FOREIGN KEY (ID_TIPOINCIDENCIA) REFERENCES TIPOINCIDENCIA (COD_TIPOINCIDENCIA),
CONSTRAINT FK_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(COD_ESTADO)
);

CREATE TABLE USUARIO(
ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
NOMBRE VARCAHR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
NICKNAME VARCAHR(50) NOT NULL,
CONTRASENA VARCHAR(30) NOT NULL,
EMAIL VARCAHR(50) NOT NULL,
IS_ACTIVO BOOLEAN NOT NULL,
ID_TIPOUSUARIO INTEGER NOT NULL,
CONSTRAINT FK_TIPO_USUARIO FOREIGN KEY  (ID_TIPOUSUARIO) REFERENCES TIPO_SUARIO(COD_USUARIO),
CONSTRAINT FK_ID_USUARIO FOREIGN KEY  (ID_USUARIO) REFERENCES INCIDENCIA(ID_USUARIO)
);
