/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaces;

import com.DAO.Incidencia;
import com.DAO.TicketDAOImpl;
import com.DAO.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev
 */
public class Admin extends javax.swing.JFrame {

    public Usuario u;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        this.setTitle("ADMINISTRADOR");
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        Usuario u = new Usuario(1, "admin", "admin", "1");
        this.u = u;
    }

    public Admin(Usuario u) {
        initComponents();
        this.setTitle("ADMINISTRADOR");
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.u = u;
    }

    public void rellenarTablaIncidencias() {
        try (TicketDAOImpl tdi = new TicketDAOImpl(this.u)) {
            ArrayList<Incidencia> al = tdi.ObtenerAllIncidencias();
            DefaultTableModel dtm = (DefaultTableModel) this.jTableIncidencias.getModel();
            dtm.setNumRows(0);
            for (Incidencia i : al) {
                Object[] array = {i.getId(), i.getIdPrioridad(), i.getIdUsuarioAfectado(), i.getIdEstado(), i.getIdUsuarioTecnico(),
                    i.getTitulo(), i.getFechaAlta(), i.getFechaUltimaModificacion(), i.getFechaFinal(), i.getIdDispositivo(),
                    i.getDescripcion(), i.getSolucion()};
                System.out.println(i);
                dtm.addRow(array);
            }
        } catch (SQLException sqle) {
            sqle.printStackTrace();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIncidencias = new javax.swing.JTable();
        botonBuscarUsuario = new javax.swing.JButton();
        textoIDUsuario = new javax.swing.JTextField();
        botonModificar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        jButtonNuevaIncidencia1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTableIncidencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prioridad", "ID afectado", "Estado", "ID técnico", "Título", "Fecha apertura", "Ultima modificacion", "Fecha cierre", "Dispositivo", "Descripción", "Solución"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableIncidencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableIncidenciasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableIncidencias);
        if (jTableIncidencias.getColumnModel().getColumnCount() > 0) {
            jTableIncidencias.getColumnModel().getColumn(0).setResizable(false);
            jTableIncidencias.getColumnModel().getColumn(1).setResizable(false);
            jTableIncidencias.getColumnModel().getColumn(2).setResizable(false);
            jTableIncidencias.getColumnModel().getColumn(3).setResizable(false);
            jTableIncidencias.getColumnModel().getColumn(4).setResizable(false);
            jTableIncidencias.getColumnModel().getColumn(5).setResizable(false);
            jTableIncidencias.getColumnModel().getColumn(6).setResizable(false);
            jTableIncidencias.getColumnModel().getColumn(7).setResizable(false);
            jTableIncidencias.getColumnModel().getColumn(8).setResizable(false);
            jTableIncidencias.getColumnModel().getColumn(9).setResizable(false);
            jTableIncidencias.getColumnModel().getColumn(10).setResizable(false);
            jTableIncidencias.getColumnModel().getColumn(11).setResizable(false);
        }

        botonBuscarUsuario.setText("Buscar");
        botonBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarUsuarioActionPerformed(evt);
            }
        });

        textoIDUsuario.setText("ID usuario");
        textoIDUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoIDUsuarioMouseClicked(evt);
            }
        });

        botonModificar.setText("Modificar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonBorrar.setText("Cerrar incidencia");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        jButtonNuevaIncidencia1.setText("Nueva incidencia");
        jButtonNuevaIncidencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaIncidencia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                        .addComponent(jButtonNuevaIncidencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarUsuario)
                    .addComponent(textoIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificar)
                    .addComponent(botonBorrar)
                    .addComponent(jButtonNuevaIncidencia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableIncidenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableIncidenciasMouseClicked
        this.botonBorrar.setEnabled(true);
        this.botonModificar.setEnabled(true);
    }//GEN-LAST:event_jTableIncidenciasMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.rellenarTablaIncidencias();
    }//GEN-LAST:event_formWindowActivated

    private void textoIDUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoIDUsuarioMouseClicked
        this.textoIDUsuario.setText("");
    }//GEN-LAST:event_textoIDUsuarioMouseClicked

    private void botonBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarUsuarioActionPerformed
        try (TicketDAOImpl tdi = new TicketDAOImpl(u)) {
            if (!textoIDUsuario.getText().equals("") || !textoIDUsuario.getText().isBlank()) {
                ArrayList<Incidencia> al = tdi.ObtenerIncidenciasPorIdUsuario(Integer.parseInt(this.textoIDUsuario.getText()));
                DefaultTableModel dtm = (DefaultTableModel) this.jTableIncidencias.getModel();
                dtm.setNumRows(0);
                for (Incidencia i : al) {
                    Object[] array = {i.getId(), i.getIdPrioridad(), i.getIdUsuarioAfectado(), i.getIdEstado(), i.getIdUsuarioTecnico(),
                        i.getTitulo(), i.getFechaAlta(), i.getFechaUltimaModificacion(), i.getFechaFinal(), i.getIdDispositivo(),
                        i.getDescripcion(), i.getSolucion()};
                    dtm.addRow(array);
                }
            } else {
                rellenarTablaIncidencias();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonBuscarUsuarioActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        NuevaIncidencia ni = new NuevaIncidencia(this.u);
        this.dispose();
        ni.setVisible(true);
        ni.requestFocus();
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        int idIncidencia = -1;
        try (TicketDAOImpl tdi = new TicketDAOImpl(this.u)) {
            DefaultTableModel dtm = (DefaultTableModel) this.jTableIncidencias.getModel();
            if (this.jTableIncidencias.getSelectedRow() != -1) {
                idIncidencia = (Integer) dtm.getValueAt(this.jTableIncidencias.getSelectedRow(), 0);
            }
            if (JOptionPane.showConfirmDialog(null, "¿De verdad deseas cerrar la incidencia?\nEsta acción es irreversible.", "OJOCUIDAO",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                // yes option
                if (idIncidencia != -1) {
                    tdi.cerrarIncidencia(idIncidencia);
                    this.rellenarTablaIncidencias();
                }
            } else {
                // no option
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonBorrarActionPerformed

    private void jButtonNuevaIncidencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaIncidencia1ActionPerformed
        NuevaIncidencia ni = new NuevaIncidencia(this.u);
        this.dispose();
        ni.setVisible(true);
        ni.requestFocus();
    }//GEN-LAST:event_jButtonNuevaIncidencia1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBuscarUsuario;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton jButtonNuevaIncidencia1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableIncidencias;
    private javax.swing.JTextField textoIDUsuario;
    // End of variables declaration//GEN-END:variables
}
